# Generated by Django 4.0.4 on 2022-05-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0006_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super',
            name='primary_ability',
        ),
        migrations.AddField(
            model_name='super',
            name='primary_ability',
            field=models.ManyToManyField(related_name='primary_ability', to='supers.power'),
        ),
        migrations.RemoveField(
            model_name='super',
            name='secondary_ability',
        ),
        migrations.AddField(
            model_name='super',
            name='secondary_ability',
            field=models.ManyToManyField(related_name='secondary_ability', to='supers.power'),
        ),
    ]
